version: "2"

services:

  cups:
    image: a0js/rpi-cups
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - ./printers.conf:/etc/cups/printers.conf
    environment:
      - CUPS_USER_ADMIN=admin
      - CUPS_USER_PASSWORD=admin
    restart: always
    privileged: true
